### ISSUE TITLE
끄투리오 지원 추가

### ISSUE THREAD

**Issue by hsheric0210** [hsheric0210/AutoKkutu#32]
현재 봉착한 난관들:

* [window.getComputedStyle()은 또 어떻게 알고 막는거지?](https://github.com/horyu1234/KKuTu/blob/e257407183580c5c3158c424e26ab5498087e3d6/Server/Game/master.js#L785)
* [이벤트 변조 감지??](https://github.com/horyu1234/KKuTu/blob/e257407183580c5c3158c424e26ab5498087e3d6/Server/Game/master.js#L815)

**Comment by hykii** [comment]
```javascript
var ee = false;
try {
    var qq = document.getElementById("element id");
    var as = qq.offsetParent;
    as = as.offsetParent;
} catch {
    ee = true;
}
if (ee == false) { /* 엘리먼트가 진짜일 때 */ }
```
로 하면 아마 작동할겁니다. 엘리먼트들을 가져와서 forEach문 안에 해당 코드를 넣어서 걸러내면 됩니다.

**Comment by hoppin-3** [comment]
안녕하십니까. 끄투 관련 깃허브를 확인하다가 알게되었는데 혹시 사용법이 어떻게 되는가요 ?

**Comment by hsheric0210** [comment]
원 레포지토리 https://github.com/horyu1234/Kkutu 에 더이상 접근할 수 없게 됨.

**Comment by hsheric0210** [comment]
지금 와서 다시 돌아보니, 아마도 다음과 같은 방법이었을 것 같다.

1. window.getComputedStyle() 감지 방법:
    해당 함수를 Proxy() 등을 이용해서 덮어씌워 놓은 다음, 정상적인 요소들에 대한 호출들은 원본 함수 호출로 redirect하고, '보호된 요소'들에 대한 호출들이 감지될 경우 이벤트 발동.

2. 이벤트 변조 감지:
    event.isTrusted 파라미터가 true인지 항상 검사하고 false일 경우 발동.
    dispatchEvent, fireEvent 등의 관련 함수들을 모두 후킹하거나 덮어씌워서 감지 코드를 미리 심어놓기

이제는 다 소용없는 방법들...
(브라우저가 사이트 스크립트를 채 로딩하기도 전에 모든 인젝션 스크립트들을 실행해 버림, 생성된 모든 요소들은 모두 완전 무작위한 이름들을 가짐)
