### ISSUE TITLE
타자대결, 단어 오류

### ISSUE THREAD

**Issue by TianaJ3** [hsheric0210/AutoKkutu#39]
타자대결은 너무 빨리 쳐져서 서버에서 튕깁니다.

**Comment by TianaJ3** [comment]
> 타자대결은 단어가 너무 빨리 쳐져서 서버가 튕깁니다. 단어는 방어단어가 너무 없습니다 (럽, 탕)와 같은

**Comment by hsheric0210** [comment]
* 타자대결에서 딜레이가 너무 짧은 문제는 설정에서 단어 입력 딜레이를 어느 정도 늘림으로써 해결하실 수 있습니다.
* 추가적인 방어 단어들은 cb03ba6d1b0b2656a5325684503b4757b157ab62 에서 추가되었습니다.
