### ISSUE TITLE
reset flag 오류(노드 추가가 안됨)

### ISSUE THREAD

**Issue by dog898996** [hsheric0210/AutoKkutu#44]
이 프로젝트에 있는 공격노드 파일을 복붙해서 노드 일괄 추가에 넣었는데 
검증과정에서 Reset flags of 슈쁘 to "KKT2". 로그와 같이 공격단어로 멀쩡히 있던 애들이 전부 reset flags라는 말과 함께 전부 일반단어로 초기화되어버렸습니다.
그 이후론 노드 일괄 추가로 아무리 노드를 추가해도 원래 공격노드였던 단어들이 단어 추천창에 공격노드로 표시되지 않습니다.

**Comment by CrushCommunism** [comment]
그거 단어 싹다 지웠다가 다시 추가해야됨 좆같음

**Comment by hsheric0210** [comment]
단어 및 노드 데이터베이스 시스템 상, 특정 단어가 공격 또는 한방 단어로 표기되기 위해서는 *먼저 해당 단어의 노드(끝말잇기의 경우 맨 뒷 글자, 앞말잇기의 경우 맨 앞 글자, 가운뎃말잇기의 경우 정 중앙의 글자 등)가 노드 목록에 추가되어 있어야 하며*, **그렇지 않은 단어들은 모두 데이터베이스 검증 과정에서 일반 단어로 전환됩니다**.

노드는 크게 두 가지 방법으로 등록될 수 있습니다:
1. 이러한 노드들은 단어 일괄 추가/제거 섹션을 사용할 때, 왼쪽 칸에 입력된 모든 단어들에 적용되는 노드의 종류를 오른쪽 아래의 체크 버튼을 통해 직접 지정하고 추가/제거 버튼을 클릭
    * 참고: '파일에서 읽어들이기', '폴더의 파일에서 읽어들이기' 기능을 사용하실 때는, 반드시 먼저 노드 종류에 해당하는 체크 버튼들을 모두 체크해 주신 다음 파일/폴더를 선택해 주세요.
2. 데이터베이스 관리 창의 오른쪽에 위치한 노드 일괄 추가/제거 섹션 사용

혹시 로그 파일 및 단어 데이터베이스 파일을 첨부해주실 수 있으신가요?
* 단어 데이터베이스 파일 (SQLite 데이터베이스 기준): 실행 파일과 동일한 폴더에 위치한 ```path.db```
* 로그 파일: ```AutoKKutu.log``` 및 이와 비슷한 이름을 가진 파일들

**Comment by hsheric0210** [comment]
해당 버그는 이제 해결되었습니다. 최신 커밋을 직접 빌드하시거나, AppVeyor로부터 최신 버전을 다운로드받으실 수 있습니다.

<details>
<summary>해당 문제의 자세한 발생 원인</summary>
1. 종류가 지정된 단어를 일괄 추가될 때, 단어 추가와 동시에 해당 단어의 <abbr title="끝말잇기 공격/한방의 경우 맨 뒷 글자, 앞말잇기 공격/한방의 경우 맨 앞 글자 등">노드</abbr>가 내부에 노드 인덱스 캐시에는 저장이 되나, 실제 데이터베이스의 노드 인덱스 테이블에 저장되지 않음. (데이터베이스에 실제로 저장하는 부분을 구현하는 것을 잊음(...))
2. '데이터베이스 검증' 기능은 시작할 때, 기존의 노드 인덱스 캐시를 모두 지우고 데이터베이스로부터 다시 로드하는 절차가 있음.
3. 1번 단어 추가 과정에서 노드 인덱스 캐시에만 추가된 새로운 노드들은 위 2번 과정에서 다 날라가 버리게 되고, 데이터베이스로부터 로드된 빈 노드 인덱스 테이블 때문에 1번 과정에서 단어들을 '한방 단어'로 추가했다고 하더라도 단어 노드 검증 과정에서 이들을 모두 다 일반 노드로 바꾸어 버리는 문제가 발생함.
</details>

<details>
<summary>한번 해당 오류가 발생한 이후로 아무리 노드 추가를 해도 단어가 공격/한방 단어로 표시되지 않던 문제의 원인</summary>
아마도 단어 추가 과정에서 데이터베이스에 이미 해당 단어가 존재하는지 검사하는 기능의 부작용으로 보입니다. 즉, <i>해당 단어는 이미 데이터베이스에 저장된 단어이기에</i> 단어 중복을 막기 위해 다시 추가되지 않는 것입니다.

원래 이와 같은 '단어의 노드와 노드 인덱스가 불일치하는 문제'가 발생하면 데이터베이스 검증을 통해 이를 복구할 수 있는데, 문제는 이 검증 기능이 문제를 일으켜 망가져 버렸음.
</details>
