### ISSUE TITLE
혹시 AutoKkutu.exe가 어딨는지 알 수 있을까요

### ISSUE THREAD

**Issue by june2007** [hsheric0210/AutoKkutu#45]
ㅈㄱㄴ

**Comment by hsheric0210** [comment]
소스코드를 직접 컴파일하시거나 README에 링크되어 있는 AppVeyor CI에서 다운받으실 수 있습니다.

2023-02-23 기준 최신 버전:
* [안정 버전](https://ci.appveyor.com/api/buildjobs/r08lim2vwfio6v62/artifacts/Windows.x64.Release.7z)
* [베타 버전](https://ci.appveyor.com/api/buildjobs/43vwjov6i3qq3tj8/artifacts/Windows.x64.Release.7z)
  * 베타 버전의 경우, ```AutoKkutu.exe```가 아닌, ```AutoKkutuGui.exe```를 실행시켜야 합니다.

파일이 7z로 압축되어 있기 때문에 압축을 해제하기 위해서는 [반디집](https://kr.bandisoft.com/bandizip/)이나 [7-zip](https://www.7-zip.org/download.html) 등이 필요합니다.

**Comment by june2007** [comment]
설명 감사합니다
