### ISSUE TITLE
(추천단어) 최대 개수 관련

### ISSUE THREAD

**Issue by keamlfea** [hsheric0210/AutoKkutu#46]
안녕하세요 만들어주신 프로그램 잘 사용중입니다
다만 질문드리고 싶은 것은 추천 단어는 한번에 최대 128개까지만 표시되는 건가요? 추천 단어를 128개 이상 확인할 수 있는 다른 방법이 있을까요? 예를 들면 제가 "이"로 시작하는 단어를 500개 가량 추가했는데 게임에서 플레이 할 때 실제 표시되는 추천 단어는 128개까지네요 128개 이후에는 표시 설정을 바꿔도 안 보이는 것 같습니다

**Comment by keamlfea** [comment]
그리고 이 프로그램 사용하면서 어제/오늘 "끄투코리아"에서 비인가 프로그램이라는 사유로 계정 2개에서 20년 정지 당했네요..
아마 현재 "끄투코리아"에서 안티치트를 업데이트 한 걸지도 모르겠습니다
그리고 티나게 플레이 하지는 않았습니다.

**Comment by keamlfea** [comment]
참고로 정지 당한 후에 아이피 변경 제대로 했습니다.(VPN 아닙니다) 둘다 레벨 25~30(약 5시간 플레이) 후에 정지 당했네요..

**Comment by hsheric0210** [comment]
늦게 답변드려 죄송합니다
1. 단어 쿼리 최대 개수 128개 제한은 버전 v1.0에서는 존재했었으나, v1.1 버전에서는 완전히 삭제되었습니다.
2. 현재 제가 아는 바로는 끄투에 적용할 수 있는 안티 치트는 크게 4가지 종류가 있습니다.
    1. '가짜' 채팅 창 또는 전송 버튼을 만들어 놓고 (`display: none` 속성으로 숨겨진 상태), 해당 채팅 창에 내용을 입력하거나 해당 버튼을 누르면 감지.
        현재 우회 가능합니다.
    2. 채팅 입력 속도 감지. 타자 속도가 너무 균일하거나, 또는 너무 빠를 때(주로 1타 간 시간 간격이 100ms 이하인 경우가 계속하여 지속될 때)
        딜레이를 100ms 이상으로 잡고, `단어 입력 시뮬레이트` 옵션을 활성화하면 우회 가능합니다.
        
        (입력 딜레이를 매우 길게 잡더라도, `단어 입력 시뮬레이트` 옵션을 켜지 않으면 단어 전체가 한 번에 입력됩니다. 이 때문에 디텍될 수도 있습니다.)

    3. window.getComputedStyle() JavaScript 함수 호출 시도 감지.
        AutoKkutu에서 window.getComputedStyle()은 위 1. 항목에서 나온 '가짜' 채팅창이나 채팅 버튼을 탐지하는 것에(더 자세히는, HTML 태그에 `display: none` 스타일 속성이 존재하는지 검사하는 것에) 사용되고 있습니다.
        (애초에 저 함수를 후킹할 수 있는 방법이 있는지도 모르겠지만) Selenium과 ChromeDriver을 조합하여, 브라우저 단에서 JavaScript로 가짜 원소를 탐지하는 대신 브라우저 외적으로 스타일 속성을 확인하는 방식으로 구현을 바꿈으로서 우회할 수 있으며, 이 방안은 현재 구현 중입니다.
        
그리고... 아마도 계정 정지는 안티 치트 때문일 수도 있지만 관리자가 돌아다니면서 확인하다가 걸리셨을 수도 있습니다. (실제로 한 번 당해봤습니다)

**Comment by hsheric0210** [comment]
몇달 전 끄코에 당시 위 글을 적을 때 발견하지 못했던 안티 치트 로직들을 발견하였습니다... 아마 이 때문으로 보입니다.
(현재 최신 버전으로는 모두 우회 가능합니다)
