### ISSUE TITLE
끄투 코리아의 단어 데이터베이스를 얻을 방법이 있나요?

### ISSUE THREAD

**Issue by kiase** [hsheric0210/AutoKkutu#54]
이 프로그램과 별개로 단어 암기를 위한 도구를 만들기 위해 끄투 코리아의 데이터베이스를 얻고 싶은데 방법이 있나요?

**Comment by kiase** [comment]
추가로 해당 프로그램의 기능으로 자음퀴즈 자동검색&입력 기능도 있으면 좋을 것 같습니다
자음퀴즈에 표시되는 초성과 단어의 주제, 힌트로 제공되는 추가 초성으로 단어를 표시하는 방식으로요

**Comment by hsheric0210** [comment]
1. 저도 끄투코리아 데이터베이스는 얻지 못했습니다...

기본 제공 데이터베이스의 단어들은 [나무위키 문서](https://namu.wiki/w/%EB%81%84%ED%88%AC/%ED%95%9C%EA%B5%AD%EC%96%B4/%EA%B8%B4%20%EB%8B%A8%EC%96%B4)나 [원본 끄투 데이터베이스 파일](https://github.com/JJoriping/KKuTu/blob/master/db.sql)로부터 얻은 것과 몇천 시간동안 사끄봇이랑 돌리면서 얻은 단어들 뿐입니다.

2. 네, 자음퀴즈 자동입력 기능도 현재 구현 예정에 있습니다.

**Comment by hsheric0210** [comment]
현재 끄코위키 단어 목록을 파싱하기 위한 크롤러를 제작하는 중입니다.

**Comment by kiase** [comment]
이건 개인적으로 불편한 점인데.. 클라이언트에서 오른쪽에 검색된 단어 목록 표시되는 부분이 창 크기를 가로로 키워도 일정 수준 이상 안커지는거 같은데 이거 때문에 긴 단어의 경우에 끝까지 안보이고 잘리는 문제가 생깁니다. 이 부분도 해결 가능하면 해결해주심 감사하겠습니다

**Comment by kiase** [comment]
혹시 그럼 현재까지 수집하신 끄코 단어 데이터베이스 공유 가능하신가요?

**Comment by hsheric0210** [comment]
끄코위키 (및 분끄위키) 크롤러는
https://github.com/hsheric0210/AutoKkutu/tree/73159b5bbf1062a20e5865569712410f9257b27f/KkukoWiki%20crawler
에서 확인하실 수 있고, 사용법 역시 README.md에 설명되어 있습니다.

제가 크롤링한 단어들은 해당 폴더의 json 파일들에 적혀 있습니다.

직접 크롤러를 실행시키실 때, `pip install -r requirements.txt` 명령을 통해 필요한 패키지들을 먼저 설치하는 것을 잊지 마세요!
