### ISSUE TITLE
현재 1.2 버전에서 전송이 되지 않는 문제가 있어 보입니다.

### ISSUE THREAD

**Issue by kiase** [hsheric0210/AutoKkutu#59]
1.1 버전이 5개월전 업데이트가 멈춰서 1.2를 빌드해서 사용하려 했으나
입력기능은 정상 작동하지만 개임 내 '전송' 버튼이 동작하지 않는 문제를 발견했습니다
(앤터, 인게임 전송 버튼, 클라이언트 전송 버튼 모두 메세지를 전송하지 못함)
이에 따라 인게임에서도 정답이 입력되지 않는 문제가 있습니다.

**Comment by mocxlbor** [comment]
끄투 코리아에서는 안되지만 다른곳에선 되는거 같습니다.

**Comment by hsheric0210** [comment]
잠재적 원인 의심 코드: https://github.com/hsheric0210/AutoKkutu/blob/73159b5bbf1062a20e5865569712410f9257b27f/AutoKkutuLib.Game.DomHandlers.JavaScript/Resources/bypassHandler.js#L14

또는, 그냥 우회에 실패해서 가짜 버튼(chatBtnf, chatBtnf2) 등을 누르고 있던 것을 안티치트 패킷 차단 기능이 간신히 막고 있던 것일 수도 있음. (이 경우, 진짜 심각한 문제)

**Comment by hsheric0210** [comment]
그리고, 비록 README에 적는 것을 깜박했지만  
최신 v1.2 버전 빌드는 https://ci.appveyor.com/project/hsheric0210/autokkutu 에서, 또는 AppVeyor 링크를 타고 들어간 뒤 좌상단의 'Current build' 버튼을 클릭하여 간편하게 다운로드 가능합니다.

**Comment by hsheric0210** [comment]
최신 버전(6395774d25bb6cd82fa42027be5fc25889d88a73)으로 끄코에서 자동 검색 및 입력 기능이 제대로 작동하는 것을 확인했습니다.

추신: 끄코에서 사용하실 때는 반드시 '입력 시뮬레이션' 옵션과 '키 입력 전송' 옵션을 활성화하신 상태로 플레이하시는 것이 좋습니다. (자세한 내용은 [여기](https://gitlab.com/-/snippets/2548135)에서 'game_input' 파트를 참고하세요.
