### ISSUE TITLE
끄코에서 딜레이가 심하게 생기는 문제

### ISSUE THREAD

**Issue by kiase** [hsheric0210/AutoKkutu#61]
하드웨어 가속이나 램 할당이 부족한건지 사끄봇이랑 1라운드정도 돌리면 정상적인 관전조차 불가능할 정도로 랙이 발생합니다.
5라운드로 게임 끝나고 나오면 30분동안 화면이 흔들리고 있습니다..ㅋㅋ
확인 부탁드립니다.

**Comment by kiase** [comment]
추가로 https://github.com/hsheric0210/AutoKkutu/issues/48 에서 해결하셨던 이슈가 다시 발생하는것으로 보입니다.
1.2 가장 최신 빌드에서 현재 구글 로그인이 되지 않는 이슈가 있습니다.(안전하지 않은 브라우저)

**Comment by hsheric0210** [comment]
아마도 커밋 6395774d25bb6cd82fa42027be5fc25889d88a73 에서부터 발생해서 커밋 8e3aeb958987d9d41d479521ea9c2a2ed2e5aff8 에서 고쳐진 `window.setTimeout`이 `window.setInterval`로 대신 작동하는 문제 때문인 것으로 보입니다.

해당 문제는 '입력 시뮬레이션' 기능과 '키 입력 이벤트 전송' 옵션이 활성화되어 있는 상태에서 매 채팅 자동 입력 시마다 발생하며, `sendKeyEvents` 함수 내부에서 키가 '떼졌다는' 이벤트를 일정 지연 시간 후에 발생시키기 위해 `window.setTimeout`을 사용한 것에서 시작되었습니다.

**Comment by kiase** [comment]
그럼 현재 해결방안이 발견되지 않은 것인가요?

**Comment by hsheric0210** [comment]
아뇨, 아마 커밋 8e3aeb958987d9d41d479521ea9c2a2ed2e5aff8에서 해당 문제가 고쳐지며 함께 해결된 것으로 보여집니다.
