### ISSUE TITLE
한방 관련 오류

### ISSUE THREAD

**Issue by sg5993** [hsheric0210/AutoKkutu#67]
줘, 면, 늄 등의 단어는 끄투코리아 기준 한방 단어가 아님에도 찾을 수 있는 단어가 없다고 뜹니다. 새로 등록을 해도 여전히 한방 단어인 줄 아는 건지 검색해도 뜨질 않네요

**Comment by hsheric0210** [comment]
넵 새로 단어를 등록하시더라도, '한방 노드'를 가지고 있다고 판단되는 단어는 검색에서 제외됩니다.
만약 해당 단어가 한방 단어가 아니라면, '단어 등록 및 제거'가 아닌, '노드 등록 및 제거' 메뉴에서 해당 노드들을 제거해 주신 다음 데이터베이스 재검증 작업을 실행시켜 주셔야 합니다.

**Comment by hsheric0210** [comment]
추가적으로, 위와 같이 비록 한방 노드에 등록되었지만 데이터베이스 상에 받아칠 수 있는 다른 단어가 발견된 경우 한방 노드에서 자동으로 제거하는 기능을 추가하겠습니다.

* [ ] 데이터베이스 검증 시, 비록 한방 노드에 등록되어 있는 단어지만 데이터베이스 상 받아칠 수 있는 단어가 존재하는 경우 한방 노드에서 제거하는 기능 추가

**Comment by sg5993** [comment]
단어 목록은 어떻게 봐야 하나요?
예를 들어 줘나 면으로 끝나는 단어가 포함된 노드를 제거하고 싶은데 찾기가 힘드네요

**Comment by hsheric0210** [comment]
단순히 해당 노드들을 제거하기 위해서는 데이베이스 관리자 창에서 해당 '줘, 면'과 같은 노드들을 **줄바꿈으로 구분하여** 노드 목록에 기입한 다음 옆의 '제거' 체크박스를 체크하고 '추가/제거' 버튼을 클릭하시면 됩니다.
그 후 반드시 '데이터베이스 검증' 작업을 수행해 주시는 것을 추천드립니다.

일단 현재로서는 단어 목록을 직접 보는 방법은 수동 검색 기능을 게임 모드를 지정하여 사용하는 방법 외에는 존재하지 않습니다.

게임 모드 지정: 끝말잇기(맨 첫 글자 일치 검색), 가운뎃말잇기(가운데 글자 일치 검색), 앞말잇기(마지막 글자 일치 검색)
예시로, '줘'로 끝나는 단어를 검색하기 위해서는 수동 검색 게임 모드를 '앞말잇기'로 지정하고 '줘'를 검색함으로서 가능합니다. 물론, 해당 '줘' 노드가 한방 노드에서 제거된 상태이어야 합니다.

또한, 단어를 제거하는 기능도 와일드카드를 지원하지 않고, 직접 단어 전체를 입력하여 지우는 기능 외에는 지원되지 않습니다. 추후 이 부분을 개선하는 기능을 추가하겠습니다.

**Comment by hsheric0210** [comment]
위에서 언급한 기능은 #82 에서 추가되었습니다.
