### ISSUE TITLE
시간 관련

### ISSUE THREAD

**Issue by sg5993** [hsheric0210/AutoKkutu#68]
시간이 촉박할 때는 장문을 치지 않고 자동으로 짧은 단어를 치게 할 수 있을까요?

**Comment by hsheric0210** [comment]
결론부터 말씀드리면, 이미 똑같은 기능이 구현되어 있습니다.

단어 입력 딜레이 기능 사용 시, 모든 후보 단어들에 대하여 `(최대 시작 딜레이) + (최대 단어 간 딜레이) * (글자 개수)`을 남은 턴 시간과 비교하고, 이를 통해 남은 턴 시간 내에 입력을 끝마칠 수 있는 단어들만 실질적 입력 후보에 포함하는 식으로 구현되어 있습니다.

이는 딜레이 랜덤 옵션에 대해서도 고려하여 구현되었기에, 먼저 최악의 딜레이 상황을 가정하고 계산을 시도한 후, 아무 것도 사용 가능한 것이 없으면 다시 최적의 딜레이 상황을 가정하고 다시 계산을 수행하여 사용 가능한 단어를 선택합니다.

이에 대한 자세하고 구체적인 구현은 여기에서 보실 수 있습니다: https://github.com/hsheric0210/AutoKkutu/blob/8ddf7e715266cd243f44b1ab467adcd156eff0a4/AutoKkutuLib/PathList.cs#L30
