### ISSUE TITLE
appveyor 단어 다 추가해서 재 빌드 해주실수있나요?

### ISSUE THREAD

**Issue by lbt433** [hsheric0210/AutoKkutu#69]
부탁드립니다.

**Comment by hsheric0210** [comment]
넵 재빌드 요청 완료하였습니다.

단어 데이터베이스는 프로그램에 기본적으로 포함되지는 않지만, 몇몇 얘시 데이터베이스들을 [여기](https://github.com/hsheric0210/AutoKkutu/tree/v1.2/Example%20Database)에서 다운로드받으실 수 있습니다.
* [오리지널 끄투 단어 데이터베이스](https://github.com/hsheric0210/AutoKkutu/raw/v1.2/Example%20Database/original_kkutu.sqlite)
* [핑크끄투 단어 데이터베이스](https://github.com/hsheric0210/AutoKkutu/raw/v1.2/Example%20Database/kkutu_pink.2023-05-25.sqlite)

단어 데이터베이스를 다운로드받으신 후에는 프로그램 실행 파일과 같은 폴더에 `path.sqlite`라는 이름으로 저장해 주세요.
데이터베이스에 관한 설정을 자세히 수정하시려면 `Servers.xml` 파일을 참조하세요. (해당 파일에서는 데이터베이스 세부 설정 뿐만 아니라 지원할 서버들, 그리고 각 서버들에 대한 핸들러까지 모두 설정하실 수 있습니다)
