### ISSUE TITLE
한방단어 관련

### ISSUE THREAD

**Issue by lbt433** [hsheric0210/AutoKkutu#70]
욤 , 윰 , 줘 등 제가 확인해본것들입니다

욤 : 욤욤공주와도둑
윰 : 윰댕
줘 : 줘쟝 ....
 
이렇게 존재하는 단어임에도 한방 단어 처리되어 작동하지 않습니다. hotfix 가능합니까?

**Comment by kiase** [comment]
직접 노드를 변경하여 수정하시기 바랍니다
제작하신분이 끄투코리아 기반이 아닌 분홍끄투 기반으로 기본 단어장을 제작하셔서 그럴껍니다
프로그램 실행 후 [데이터베이스 관리] 버튼 클릭하시면 노드 변경할 수 있는 부분 나와있습니다

**Comment by lbt433** [comment]
> 직접 노드를 변경하여 수정하시기 바랍니다 제작하신분이 끄투코리아 기반이 아닌 분홍끄투 기반으로 기본 단어장을 제작하셔서 그럴껍니다 프로그램 실행 후 [데이터베이스 관리] 버튼 클릭하시면 노드 변경할 수 있는 부분 나와있습니다

그래도 안되어서 그냥 sqlite 새로 작성했더니 됩니다 도움주셔서 감사합니다 ^^

**Comment by hsheric0210** [comment]
#82 에서 데이터베이스 상에 받아칠 수 있는 단어가 이미 존재하는 한방 노드들은 자동으로 검증 작업 실행 시 제거하는 기능이 추가되었습니다.
