### ISSUE TITLE
다운오류

### ISSUE THREAD

**Issue by Chooonche** [hsheric0210/AutoKkutu#72]
Artifacts에서 파일이 보이지 않습니다

**Comment by hsheric0210** [comment]
넵 AppVeyor 재컴파일을 실행하였습니다.
또한, 혹시라도 한 달 뒤에 다시 파일이 만료될 상황을 대비하여 [릴리즈 목록](https://github.com/hsheric0210/AutoKkutu/releases)에도 파일을 업로드하였습니다.
