### ISSUE TITLE
단어 데이터베이스 자동 변경

### ISSUE THREAD

**Issue by cringe-idiot** [hsheric0210/AutoKkutu#73]
드롭다운을 통하여 접속 서버를 바꿀 때마다 데이터베이스를 자동으로 변경해주는 기능을 추가해주셨으면 합니다.

**Comment by hsheric0210** [comment]
이미 구현되어 있습니다.

자세한 설정은 `Servers.xml`에서 가능합니다. 맨 윗쪽에 주석 쳐진 내용을 참고하시면 됩니다.
(만약 `Servers.xml` 파일이 보이지 않는다면 `AutoKkutuGui.exe`를 한 번 켰다 꺼 주시면 됩니다)

예시로, 끄코에서는 기본 데이터베이스 파일 대신 `kkuko.sqlite`을 사용하시려면
```xml
<server>
    <url>https://kkutu.co.kr</url>
    <domHandler>BasicBypassDomHandler</domHandler>
</server>
```

에서

```xml
<server>
    <url>https://kkutu.co.kr</url>
    <domHandler>BasicBypassDomHandler</domHandler>
    <database type="sqlite">Data Source=kkuko.sqlite</database>
</server>
```

와 같이 database 요소를 추가해 주면 됩니다.

이외에도 MySQL(MariaDB), PostgreSQL 등을 지원합니다. 이들을 사용하시려면 database 원소의 내부 값에 접속 문자열을 넣어 주시면 됩니다.
