### ISSUE TITLE
단어 오류

### ISSUE THREAD

**Issue by sosing1235** [hsheric0210/AutoKkutu#75]
게임이 끝난 뒤에도 썼던 단어들이 제외되어 있습니다

**Comment by hsheric0210** [comment]
혹시 게임이 끝난 후가 아니라, 게임의 매 라운드 변경 시에는 이미 사용한 단어들을 다시 사용할 수 있나요?
아마도 라운드 변경 시에만 이미 사용한 단어 목록을 초기화하도록 구현해서 발생한 문제 같습니다.

https://github.com/hsheric0210/AutoKkutu/blob/46ff6803dd9ddab84af7a8ff74e3bb9bab73a25a/AutoKkutuLib/AutoKkutu.Mediator.cs#L40

빠르게 해결하도록 하겠습니다.

**Comment by hsheric0210** [comment]
일단 커밋 8a6338645391043aa2b32cdf47df7a6f0ddac97e 에서 수정되었습니다.
