### ISSUE TITLE
딜레이 설정 저장이 안됩니다.

### ISSUE THREAD

**Issue by HYUNIGRAM** [hsheric0210/AutoKkutu#77]
딜레이 설정을 늘리고 적용을 눌러도 기본값으로 바뀌네요.
appdata local 파일로 제가 바꿔도 적용이 안되네요.
확인해주시면 감사하겠습니다. 
감사합니다

**Comment by hsheric0210** [comment]
9186adbf3c6e365a2d9f9a0f69462847fb971c5e 에서 해결되었습니다.

**Comment by HYUNIGRAM** [comment]
감사합니다
