### ISSUE TITLE
unhandled exception 오류

### ISSUE THREAD

**Issue by kimhs0427** [hsheric0210/AutoKkutu#78]
ReleaseSelenium.x64 여기서 
AutoKkutuGui 실행 시 unhandled exception 뜨면서 실행이 안되네요..

**Comment by hsheric0210** [comment]
Selenium 버전 이슈와 관련된 오류같아 보이네요
https://github.com/SeleniumHQ/selenium/issues/13081

**Comment by hsheric0210** [comment]
9186adbf3c6e365a2d9f9a0f69462847fb971c5e 에서 의존성 버전 업데이트를 통해 해결되었습니다.

**Comment by kiase** [comment]
해결된 빌드는 어디서 받을 수 있나요?

**Comment by hsheric0210** [comment]
[AppVeyor 링크](https://ci.appveyor.com/project/hsheric0210/autokkutu)에서 다운로드 가능합니다
기본적으로 README 상단의 AppVeyor 버튼 (build | passing 버튼) 누르면 이동하실 수 있습니다.
