### ISSUE TITLE
사전 검증

### ISSUE THREAD

**Issue by BING87238** [hsheric0210/AutoKkutu#97]
데이터 베이스에서 사전검증 체크 하고 폴더의 파일에서 읽어들이기 클릭하고 Example Node Data 와 같은 폴더 클릭하고 하면 AutoKkutu 가 멈춤니다

**Comment by hsheric0210** [comment]
사전검증 기능이면 아마 온라인 끄투 사전이랑 단어를 하나하나 맞춰보면서 존재하는 단어인지 검사한 후 단어를 추가하는 기능이었던 것으로 기억하는데...

현재 그 기능은 너무 비효율적이기도 하고(무엇보다 단어를 하나하나 검색하면서 소요되는 시간이 너무나도 길어서) 완전히 비활성화해 놓은 상태여서 활성화하기만 해도 오류를 발생시키는 걸로 알고 있습니다.

일단 해당 기능을 끄고 사용하시길 부탁드립니다.
